# Project Football Project 3
## Deliverable: Scrape and Analyze Player Data
Create a Beautiful Soup object and use it to scrape the data in the HTML table.

Note that this can also be achieved by using the Pandas `read_html` function. However, use Beautiful Soup here to continue sharpening your web scraping skills.

In [1]:
# Import relevant libraries
from splinter import Browser
from bs4 import BeautifulSoup as soup
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
browser = Browser('chrome')

In [3]:
#url for Player goals Stats seasons 2017_2019 to 2021_2022
url_1718_player = "https://fbref.com/en/comps/13/2017-2018/stats/2017-2018-Ligue-1-Stats"
url_1819_player = "https://fbref.com/en/comps/13/2018-2019/stats/2018-2019-Ligue-1-Stats"
url_1920_player = "https://fbref.com/en/comps/13/2019-2020/stats/2019-2020-Ligue-1-Stats"
url_2021_player = "https://fbref.com/en/comps/13/2020-2021/stats/2020-2021-Ligue-1-Stats"
url_2122_player = "https://fbref.com/en/comps/13/2021-2022/stats/2021-2022-Ligue-1-Stats"

In [4]:
# Visit the website
urls = [url_1718_player, url_1819_player, url_1920_player, url_2021_player, url_2122_player]
Col = []
dt = []
for url in urls:
    browser.visit(url)
    browser.is_element_present_by_css('div.list_text', wait_time=1)
    html = browser.html
    player_soup = soup(html, 'html.parser')
    table = player_soup.find('table', class_='min_width sortable stats_table shade_zero now_sortable sticky_table eq2 re2 le2')
    # Create an empty list
    columns = []
    data = []
    # Loop through the scraped data to create a list of rows

    headings = table.find_all('th', 'data.stat')
    for heading in headings:
        columns.append(heading.get_data-stat())

    rows = table.find_all('tr')

    for row in rows:
        items = []
        row_data = row.find_all('td')
        for i in row_data:
            items.append(i.text)
        data.append(items)
    Col.append(columns)
    dt.append(data)

In [5]:
print(Col[4])

[]

### Step 2: Create Dataframes

In [6]:
# Create a Pandas DataFrame for 2017-2018 season by using the list of rows and a list of the column names
player17_18_df = pd.DataFrame(dt[0], columns = ['Player','Nation','Pos','Squad','Age','Born','MP',
                                          'Starts','Min','90s','Gls','Ast','G+A','G-PK','PK','PKatt','CrdY',
                                           'CrdR','xG','npxG','xAG','npxG+xAG','PrgC','PrgP','PrgR','Gls','Ast',
                                            'G+A','G-PK','G+A-PK','xG','xAG','xG+xAG','npxG','npxG+xAG','Matches'])
player17_18_df['Seasons']= '2017-2018'
player17_18_df = player17_18_df[2:]
player17_18_df.head()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,Seasons
2,Aymen Abdennour,tn TUN,DF,Marseille,27,1989,8,6,499,5.5,...,0.00,0.00,0.00,0.02,0.00,0.02,0.02,0.02,Matches,2017-2018
3,Mehdi Abeid,dz ALG,MF,Dijon,24,1992,19,14,"1,176",13.1,...,0.08,0.00,0.08,0.07,0.02,0.10,0.07,0.10,Matches,2017-2018
4,Khaled Adénon,bj BEN,DF,Amiens,32,1985,34,32,"2,921",32.5,...,0.03,0.00,0.03,0.02,0.01,0.03,0.02,0.03,Matches,2017-2018
5,Yacine Adli,fr FRA,FW,Paris S-G,17,2000,1,0,8,0.1,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,2017-2018
6,Ruben Aguilar,fr FRA,DF,Montpellier,24,1993,31,27,"2,459",27.3,...,0.07,0.00,0.07,0.03,0.13,0.16,0.03,0.16,Matches,2017-2018

In [7]:
# Create a Pandas DataFrame for 2018-2019 season by using the list of rows and a list of the column names
player18_19_df = pd.DataFrame(dt[1], columns = ['Player','Nation','Pos','Squad','Age','Born','MP',
                                          'Starts','Min','90s','Gls','Ast','G+A','G-PK','PK','PKatt','CrdY',
                                           'CrdR','xG','npxG','xAG','npxG+xAG','PrgC','PrgP','PrgR','Gls','Ast',
                                            'G+A','G-PK','G+A-PK','xG','xAG','xG+xAG','npxG','npxG+xAG','Matches'])
player18_19_df['Seasons']= '2018-2019'
player18_19_df = player18_19_df[2:]

player18_19_df.head()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,Seasons
2,Ismael Aaneba,fr FRA,DF,Strasbourg,19,1999,3,3,204,2.3,...,0.00,0.00,0.00,0.00,0.17,0.17,0.00,0.17,Matches,2018-2019
3,Yunis Abdelhamid,ma MAR,DF,Reims,30,1987,38,38,"3,420",38.0,...,0.00,0.00,0.00,0.04,0.00,0.05,0.04,0.05,Matches,2018-2019
4,Mehdi Abeid,dz ALG,MF,Dijon,25,1992,26,23,"2,023",22.5,...,0.13,0.09,0.09,0.13,0.07,0.20,0.10,0.17,Matches,2018-2019
5,Charles Abi,fr FRA,"DF,FW",Saint-Étienne,18,2000,3,0,32,0.4,...,0.00,0.00,0.00,0.17,0.12,0.29,0.17,0.29,Matches,2018-2019
6,Khaled Adénon,bj BEN,DF,Amiens,33,1985,23,22,"1,994",22.2,...,0.00,0.00,0.00,0.03,0.01,0.04,0.03,0.04,Matches,2018-2019

In [8]:
# Create a Pandas DataFrame for 2019- 2020 season by using the list of rows and a list of the column names
player19_20_df = pd.DataFrame(dt[2], columns = ['Player','Nation','Pos','Squad','Age','Born','MP',
                                          'Starts','Min','90s','Gls','Ast','G+A','G-PK','PK','PKatt','CrdY',
                                           'CrdR','xG','npxG','xAG','npxG+xAG','PrgC','PrgP','PrgR','Gls','Ast',
                                            'G+A','G-PK','G+A-PK','xG','xAG','xG+xAG','npxG','npxG+xAG','Matches'])
player19_20_df['Seasons']= '2019-2020'
player19_20_df = player19_20_df[2:]
player19_20_df.head()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,Seasons
2,Yunis Abdelhamid,ma MAR,DF,Reims,31,1987,28,28,"2,520",28.0,...,0.11,0.11,0.11,0.06,0.04,0.10,0.06,0.10,Matches,2019-2020
3,Mehdi Abeid,dz ALG,MF,Nantes,26,1992,25,20,"1,817",20.2,...,0.15,0.05,0.15,0.07,0.09,0.16,0.07,0.16,Matches,2019-2020
4,Charles Abi,fr FRA,FW,Saint-Étienne,19,2000,15,6,623,6.9,...,0.00,0.00,0.00,0.05,0.17,0.22,0.05,0.22,Matches,2019-2020
5,Amine Adli,fr FRA,"MF,FW",Toulouse,19,2000,4,0,46,0.5,...,0.00,0.00,0.00,0.00,0.13,0.13,0.00,0.13,Matches,2019-2020
6,Yacine Adli,fr FRA,MF,Bordeaux,19,2000,21,11,"1,020",11.3,...,0.53,0.26,0.53,0.07,0.19,0.26,0.07,0.26,Matches,2019-2020

In [9]:
# Create a Pandas DataFrame for 2020-2021 season by using the list of rows and a list of the column names
player20_21_df = pd.DataFrame(dt[3], columns = ['Player','Nation','Pos','Squad','Age','Born','MP',
                                          'Starts','Min','90s','Gls','Ast','G+A','G-PK','PK','PKatt','CrdY',
                                           'CrdR','xG','npxG','xAG','npxG+xAG','PrgC','PrgP','PrgR','Gls','Ast',
                                            'G+A','G-PK','G+A-PK','xG','xAG','xG+xAG','npxG','npxG+xAG','Matches'])
player20_21_df['Seasons']= '2020-2021'
player20_21_df = player20_21_df[2:]
player20_21_df.head()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,Seasons
2,Ismael Aaneba,fr FRA,DF,Strasbourg,21,1999,2,0,11,0.1,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,2020-2021
3,Yunis Abdelhamid,ma MAR,DF,Reims,32,1987,33,33,"2,889",32.1,...,0.09,0.09,0.09,0.06,0.01,0.07,0.06,0.07,Matches,2020-2021
4,Mehdi Abeid,dz ALG,MF,Nantes,27,1992,18,15,"1,320",14.7,...,0.00,0.00,0.00,0.07,0.05,0.12,0.07,0.12,Matches,2020-2021
5,Laurent Abergel,fr FRA,MF,Lorient,27,1993,38,32,"2,963",32.9,...,0.12,0.09,0.12,0.05,0.05,0.10,0.05,0.10,Matches,2020-2021
6,Charles Abi,fr FRA,"FW,MF",Saint-Étienne,20,2000,24,9,912,10.1,...,0.49,0.30,0.49,0.21,0.03,0.24,0.21,0.24,Matches,2020-2021

In [10]:
# Create a Pandas DataFrame for 2021-2022 season by using the list of rows and a list of the column names
player21_22_df = pd.DataFrame(dt[4], columns = ['Player','Nation','Pos','Squad','Age','Born','MP',
                                          'Starts','Min','90s','Gls','Ast','G+A','G-PK','PK','PKatt','CrdY',
                                           'CrdR','xG','npxG','xAG','npxG+xAG','PrgC','PrgP','PrgR','Gls','Ast',
                                            'G+A','G-PK','G+A-PK','xG','xAG','xG+xAG','npxG','npxG+xAG','Matches'])
player21_22_df['Seasons']= '2021-2022'
player21_22_df = player21_22_df[2:]
player21_22_df.head()

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,Seasons
2,Yunis Abdelhamid,ma MAR,DF,Reims,33,1987,34,34,"2,983",33.1,...,0.06,0.06,0.06,0.04,0.02,0.06,0.04,0.06,Matches,2021-2022
3,Salis Abdul Samed,gh GHA,MF,Clermont Foot,21,2000,31,29,"2,462",27.4,...,0.04,0.04,0.04,0.03,0.03,0.06,0.03,0.06,Matches,2021-2022
4,Laurent Abergel,fr FRA,MF,Lorient,28,1993,34,34,"2,956",32.8,...,0.06,0.00,0.06,0.04,0.11,0.16,0.04,0.16,Matches,2021-2022
5,Charles Abi,fr FRA,FW,Saint-Étienne,21,2000,1,1,45,0.5,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,Matches,2021-2022
6,Matthis Abline,fr FRA,FW,Rennes,18,2003,7,1,103,1.1,...,0.00,0.00,0.00,0.24,0.00,0.24,0.24,0.24,Matches,2021-2022

In [11]:
# Combine each seasons dataframe into 1
player_all_seasons_df = pd.concat([player17_18_df, player18_19_df, player19_20_df, player20_21_df, player21_22_df])
player_all_seasons_df.sample(100)

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,Seasons
259,Clément Grenier,fr FRA,"MF,FW",Rennes,29,1991,23,12,"1,078",12.0,...,0.58,0.25,0.50,0.22,0.19,0.40,0.15,0.34,Matches,2020-2021
49,Jonathan Bamba,fr FRA,"FW,MF",Lille,23,1996,26,22,"1,937",21.5,...,0.23,0.00,0.19,0.26,0.12,0.39,0.15,0.28,Matches,2019-2020
589,Chimuanya Ugochukwu,fr FRA,MF,Rennes,16,2004,3,1,65,0.7,...,0.00,0.00,0.00,0.19,0.00,0.19,0.19,0.19,Matches,2020-2021
372,Florian Miguel,fr FRA,DF,Nîmes,21,1996,13,12,"1,117",12.4,...,0.08,0.00,0.08,0.09,0.09,0.18,0.09,0.18,Matches,2018-2019
200,Zinedine Ferhat,dz ALG,"FW,MF",Nîmes,26,1993,26,25,"2,246",25.0,...,0.28,0.12,0.28,0.17,0.22,0.39,0.17,0.39,Matches,2019-2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270,Jules Koundé,fr FRA,DF,Bordeaux,18,1998,18,17,"1,589",17.7,...,0.11,0.11,0.11,0.07,0.00,0.08,0.07,0.08,Matches,2017-2018
141,Clément Depres,fr FRA,FW,Nîmes,23,1994,17,4,441,4.9,...,0.82,0.82,0.82,0.46,0.03,0.50,0.46,0.50,Matches,2018-2019
438,Rafael,br BRA,DF,Lyon,27,1990,24,22,"1,812",20.1,...,0.15,0.05,0.15,0.03,0.14,0.18,0.03,0.18,Matches,2017-2018
96,Eduardo Camavinga,fr FRA,MF,Rennes,15,2002,7,4,364,4.0,...,0.00,0.00,0.00,0.02,0.07,0.09,0.02,0.09,Matches,2018-2019
54,Yassine Benzia,dz ALG,"MF,FW",Lille,22,1994,31,30,"2,288",25.4,...,0.24,0.04,0.24,0.06,0.22,0.27,0.06,0.27,Matches,2017-2018

In [12]:
# Drop unwated Columns
final_player_df = player_all_seasons_df[['Player', 'Squad', 'MP', 'Starts', 'Min', '90s', 'Gls', 'Seasons']]
final_player_df.head()

            Player        Squad  MP Starts    Min   90s Gls   Gls    Seasons
2  Aymen Abdennour    Marseille   8      6    499   5.5   0  0.00  2017-2018
3      Mehdi Abeid        Dijon  19     14  1,176  13.1   0  0.00  2017-2018
4    Khaled Adénon       Amiens  34     32  2,921  32.5   0  0.00  2017-2018
5      Yacine Adli    Paris S-G   1      0      8   0.1   0  0.00  2017-2018
6    Ruben Aguilar  Montpellier  31     27  2,459  27.3   0  0.00  2017-2018

In [13]:
final_player_df = final_player_df.rename(columns={'Gls':'Goals'})
final_player_df.head()

            Player        Squad  MP Starts    Min   90s Goals Goals    Seasons
2  Aymen Abdennour    Marseille   8      6    499   5.5     0  0.00  2017-2018
3      Mehdi Abeid        Dijon  19     14  1,176  13.1     0  0.00  2017-2018
4    Khaled Adénon       Amiens  34     32  2,921  32.5     0  0.00  2017-2018
5      Yacine Adli    Paris S-G   1      0      8   0.1     0  0.00  2017-2018
6    Ruben Aguilar  Montpellier  31     27  2,459  27.3     0  0.00  2017-2018

In [14]:
# Add League Column
final_player_df['League'] = 'Ligue 1'
final_player_df.head(100)

,Player,Squad,MP,Starts,Min,90s,Goals,Goals,Seasons,League
2,Aymen Abdennour,Marseille,8,6,499,5.5,0,0.00,2017-2018,Ligue 1
3,Mehdi Abeid,Dijon,19,14,"1,176",13.1,0,0.00,2017-2018,Ligue 1
4,Khaled Adénon,Amiens,34,32,"2,921",32.5,0,0.00,2017-2018,Ligue 1
5,Yacine Adli,Paris S-G,1,0,8,0.1,0,0.00,2017-2018,Ligue 1
6,Ruben Aguilar,Montpellier,31,27,"2,459",27.3,0,0.00,2017-2018,Ligue 1
...,...,...,...,...,...,...,...,...,...,...
97,Pape Cheikh Diop,Lyon,1,0,10,0.1,0,0.00,2017-2018,Ligue 1
98,Saliou Ciss,Angers,3,2,144,1.6,0,0.00,2017-2018,Ligue 1
99,Issa Cissokho,Amiens,19,18,"1,630",18.1,0,0.00,2017-2018,Ligue 1
100,Marcus Coco,Guingamp,29,17,"1,587",17.6,2,0.11,2017-2018,Ligue 1
101,Renaud Cohade,Metz,38,38,"3,298",36.6,1,0.03,2017-2018,Ligue 1

In [15]:
# Write the data to a CSV

final_player_df.to_csv('Data/player_Ligue_1.csv', index=False)

In [16]:
browser.quit()