In [1]:
# Import Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
from scipy.stats import linregress

In [2]:
# Get summary tables for each of the last 5 seasons
table_13 = pd.read_html('https://fbref.com/en/comps/9/2012-2013/2012-2013-Premier-League-Stats')
table_14 = pd.read_html('https://fbref.com/en/comps/9/2013-2014/2013-2014-Premier-League-Stats')
table_15 = pd.read_html('https://fbref.com/en/comps/9/2014-2015/2014-2015-Premier-League-Stats')
table_16 = pd.read_html('https://fbref.com/en/comps/9/2015-2016/2015-2016-Premier-League-Stats')
table_17 = pd.read_html('https://fbref.com/en/comps/9/2016-2017/2016-2017-Premier-League-Stats')
table_18 = pd.read_html('https://fbref.com/en/comps/9/2017-2018/2017-2018-Premier-League-Stats')
table_19 = pd.read_html('https://fbref.com/en/comps/9/2018-2019/2018-2019-Premier-League-Stats')
table_20 = pd.read_html('https://fbref.com/en/comps/9/2019-2020/2019-2020-Premier-League-Stats')
table_21 = pd.read_html('https://fbref.com/en/comps/9/2020-2021/2020-2021-Premier-League-Stats')
table_22 = pd.read_html('https://fbref.com/en/comps/9/2021-2022/2021-2022-Premier-League-Stats')
table_23 = pd.read_html('https://fbref.com/en/comps/9/Premier-League-Stats')

EPL_2013_summary_df = pd.DataFrame(table_13[0])
EPL_2014_summary_df = pd.DataFrame(table_14[0])
EPL_2015_summary_df = pd.DataFrame(table_15[0])
EPL_2016_summary_df = pd.DataFrame(table_16[0])
EPL_2017_summary_df = pd.DataFrame(table_17[0])
EPL_2018_summary_df = pd.DataFrame(table_18[0])
EPL_2019_summary_df = pd.DataFrame(table_19[0])
EPL_2020_summary_df = pd.DataFrame(table_20[0])
EPL_2021_summary_df = pd.DataFrame(table_21[0])
EPL_2022_summary_df = pd.DataFrame(table_22[0])
EPL_2023_summary_df = pd.DataFrame(table_23[0])
EPL_2013_summary_df.head()

,Rk,Squad,MP,W,D,L,GF,GA,GD,Pts,Pts/MP,Attendance,Top Team Scorer,Goalkeeper,Notes
0,1,Manchester Utd,38,28,5,5,86,43,43,89,2.34,75530,Robin van Persie - 26,David de Gea,→ Champions League via league finish
1,2,Manchester City,38,23,9,6,66,34,32,78,2.05,46974,Edin Džeko - 14,Joe Hart,→ Champions League via league finish
2,3,Chelsea,38,22,9,7,75,39,36,75,1.97,41462,Frank Lampard - 15,Petr Čech,→ Champions League via league finish
3,4,Arsenal,38,21,10,7,72,37,35,73,1.92,60079,Theo Walcott - 14,Wojciech Szczęsny,→ Champions League via league finish
4,5,Tottenham,38,21,9,8,66,46,20,72,1.89,36066,Gareth Bale - 21,Hugo Lloris,→ Europa League via league finish

In [3]:
# Get 2nd summary table (index[2])for each season
sum_table_13 = pd.read_html('https://fbref.com/en/comps/9/2012-2013/2012-2013-Premier-League-Stats')
sum_table_14 = pd.read_html('https://fbref.com/en/comps/9/2013-2014/2013-2014-Premier-League-Stats')
sum_table_15 = pd.read_html('https://fbref.com/en/comps/9/2014-2015/2014-2015-Premier-League-Stats')
sum_table_16 = pd.read_html('https://fbref.com/en/comps/9/2015-2016/2015-2016-Premier-League-Stats')
sum_table_17 = pd.read_html('https://fbref.com/en/comps/9/2016-2017/2016-2017-Premier-League-Stats')
sum_table_18 = pd.read_html('https://fbref.com/en/comps/9/2017-2018/2017-2018-Premier-League-Stats')
sum_table_19 = pd.read_html('https://fbref.com/en/comps/9/2018-2019/2018-2019-Premier-League-Stats')
sum_table_20 = pd.read_html('https://fbref.com/en/comps/9/2019-2020/2019-2020-Premier-League-Stats')
sum_table_21 = pd.read_html('https://fbref.com/en/comps/9/2020-2021/2020-2021-Premier-League-Stats')
sum_table_22 = pd.read_html('https://fbref.com/en/comps/9/2021-2022/2021-2022-Premier-League-Stats')
sum_table_23 = pd.read_html('https://fbref.com/en/comps/9/Premier-League-Stats')

EPL_2013_summary2_df = pd.DataFrame(sum_table_13[2])
EPL_2014_summary2_df = pd.DataFrame(sum_table_14[2])
EPL_2015_summary2_df = pd.DataFrame(sum_table_15[2])
EPL_2016_summary2_df = pd.DataFrame(sum_table_16[2])
EPL_2017_summary2_df = pd.DataFrame(sum_table_17[2])
EPL_2018_summary2_df = pd.DataFrame(sum_table_18[2])
EPL_2019_summary2_df = pd.DataFrame(sum_table_19[2])
EPL_2020_summary2_df = pd.DataFrame(sum_table_20[2])
EPL_2021_summary2_df = pd.DataFrame(sum_table_21[2])
EPL_2022_summary2_df = pd.DataFrame(sum_table_22[2])
EPL_2023_summary2_df = pd.DataFrame(sum_table_23[2])
EPL_2013_summary2_df.head()

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
               Squad               # Pl                Age               Poss
0            Arsenal                 26               25.6                NaN
1        Aston Villa                 28               24.1                NaN
2            Chelsea                 26               26.4                NaN
3            Everton                 23               28.8                NaN
4             Fulham                 29               30.4                NaN

  Playing Time                Performance      ...                          \
            MP Starts Min 90s         Gls Ast  ... G-PK PK PKatt CrdY CrdR
0           38    418 NaN NaN          69  54  ...   64  5     6   37    4
1           38    418 NaN NaN          47  34  ...   44  3     3   72    3
2           38    418 NaN NaN          71  50  ...   62  9    11   51    3
3           38    418 NaN NaN          53  42  ...   51  2     2   59    3
4           38    418 NaN NaN          45  32  ...   39  6     6   48    3

  Per 90 Minutes
             Gls   Ast   G+A  G-PK G+A-PK
0           1.82  1.42  3.24  1.68   3.11
1           1.24  0.89  2.13  1.16   2.05
2           1.87  1.32  3.18  1.63   2.95
3           1.39  1.11  2.50  1.34   2.45
4           1.18  0.84  2.03  1.03   1.87

[5 rows x 21 columns]

In [4]:
# Remove upper level to allow for merging with other tables
EPL_2013_summary2_df = EPL_2013_summary2_df.droplevel(0, axis = 1)
EPL_2014_summary2_df = EPL_2014_summary2_df.droplevel(0, axis = 1)
EPL_2015_summary2_df = EPL_2015_summary2_df.droplevel(0, axis = 1)
EPL_2016_summary2_df = EPL_2016_summary2_df.droplevel(0, axis = 1)
EPL_2017_summary2_df = EPL_2017_summary2_df.droplevel(0, axis = 1)
EPL_2018_summary2_df = EPL_2018_summary2_df.droplevel(0, axis = 1)
EPL_2019_summary2_df = EPL_2019_summary2_df.droplevel(0, axis = 1)
EPL_2020_summary2_df = EPL_2020_summary2_df.droplevel(0, axis = 1)
EPL_2021_summary2_df = EPL_2021_summary2_df.droplevel(0, axis = 1)
EPL_2022_summary2_df = EPL_2022_summary2_df.droplevel(0, axis = 1)
EPL_2023_summary2_df = EPL_2023_summary2_df.droplevel(0, axis = 1)

In [5]:
# Get wages table for each of the last 5 seasons
EPL_wages_13 = pd.read_html('https://fbref.com/en/comps/9/2012-2013/wages/2012-2013-Premier-League-Wages')
EPL_wages_14 = pd.read_html('https://fbref.com/en/comps/9/2013-2014/wages/2013-2014-Premier-League-Wages')
EPL_wages_15 = pd.read_html('https://fbref.com/en/comps/9/2014-2015/wages/2014-2015-Premier-League-Wages')
EPL_wages_16 = pd.read_html('https://fbref.com/en/comps/9/2015-2016/wages/2015-2016-Premier-League-Wages')
EPL_wages_17 = pd.read_html('https://fbref.com/en/comps/9/2016-2017/wages/2016-2017-Premier-League-Wages')
EPL_wages_18 = pd.read_html('https://fbref.com/en/comps/9/2017-2018/wages/2017-2018-Premier-League-Wages')
EPL_wages_19 = pd.read_html('https://fbref.com/en/comps/9/2018-2019/wages/2018-2019-Premier-League-Wages')
EPL_wages_20 = pd.read_html('https://fbref.com/en/comps/9/2019-2020/wages/2019-2020-Premier-League-Wages')
EPL_wages_21 = pd.read_html('https://fbref.com/en/comps/9/2020-2021/wages/2020-2021-Premier-League-Wages')
EPL_wages_22 = pd.read_html('https://fbref.com/en/comps/9/2021-2022/wages/2021-2022-Premier-League-Wages')
EPL_wages_23 = pd.read_html('https://fbref.com/en/comps/9/wages/Premier-League-Wages')

EPL_2013_wages_df = pd.DataFrame(EPL_wages_13[0])
EPL_2014_wages_df = pd.DataFrame(EPL_wages_14[0])
EPL_2015_wages_df = pd.DataFrame(EPL_wages_15[0])
EPL_2016_wages_df = pd.DataFrame(EPL_wages_16[0])
EPL_2017_wages_df = pd.DataFrame(EPL_wages_17[0])
EPL_2018_wages_df = pd.DataFrame(EPL_wages_18[0])
EPL_2019_wages_df = pd.DataFrame(EPL_wages_19[0])
EPL_2020_wages_df = pd.DataFrame(EPL_wages_20[0])
EPL_2021_wages_df = pd.DataFrame(EPL_wages_21[0])
EPL_2022_wages_df = pd.DataFrame(EPL_wages_22[0])
EPL_2023_wages_df = pd.DataFrame(EPL_wages_23[0])

HTTPError: HTTP Error 429: Too Many Requests

In [ ]:
# Merge wages and season summary for each season
EPL_2013_merged_df = pd.merge(EPL_2013_wages_df, EPL_2013_summary_df, how="left", on=['Squad'])
EPL_2014_merged_df = pd.merge(EPL_2014_wages_df, EPL_2014_summary_df, how="left", on=['Squad'])
EPL_2015_merged_df = pd.merge(EPL_2015_wages_df, EPL_2015_summary_df, how="left", on=['Squad'])
EPL_2016_merged_df = pd.merge(EPL_2016_wages_df, EPL_2016_summary_df, how="left", on=['Squad'])
EPL_2017_merged_df = pd.merge(EPL_2017_wages_df, EPL_2017_summary_df, how="left", on=['Squad'])
EPL_2018_merged_df = pd.merge(EPL_2018_wages_df, EPL_2018_summary_df, how="left", on=['Squad'])
EPL_2019_merged_df = pd.merge(EPL_2019_wages_df, EPL_2019_summary_df, how="left", on=['Squad'])
EPL_2020_merged_df = pd.merge(EPL_2020_wages_df, EPL_2020_summary_df, how="left", on=['Squad'])
EPL_2021_merged_df = pd.merge(EPL_2021_wages_df, EPL_2021_summary_df, how="left", on=['Squad'])
EPL_2022_merged_df = pd.merge(EPL_2022_wages_df, EPL_2022_summary_df, how="left", on=['Squad'])
EPL_2023_merged_df = pd.merge(EPL_2023_wages_df, EPL_2023_summary_df, how="left", on=['Squad'])
EPL_2023_merged_df.head()

In [ ]:
# Merge in summary table#2 for each season
EPL_2013_complete_df = pd.merge(EPL_2013_merged_df, EPL_2013_summary2_df, how="left", on=['Squad'])
EPL_2014_complete_df = pd.merge(EPL_2014_merged_df, EPL_2014_summary2_df, how="left", on=['Squad'])
EPL_2015_complete_df = pd.merge(EPL_2015_merged_df, EPL_2015_summary2_df, how="left", on=['Squad'])
EPL_2016_complete_df = pd.merge(EPL_2016_merged_df, EPL_2016_summary2_df, how="left", on=['Squad'])
EPL_2017_complete_df = pd.merge(EPL_2017_merged_df, EPL_2017_summary2_df, how="left", on=['Squad'])
EPL_2018_complete_df = pd.merge(EPL_2018_merged_df, EPL_2018_summary2_df, how="left", on=['Squad'])
EPL_2019_complete_df = pd.merge(EPL_2019_merged_df, EPL_2019_summary2_df, how="left", on=['Squad'])
EPL_2020_complete_df = pd.merge(EPL_2020_merged_df, EPL_2020_summary2_df, how="left", on=['Squad'])
EPL_2021_complete_df = pd.merge(EPL_2021_merged_df, EPL_2021_summary2_df, how="left", on=['Squad'])
EPL_2022_complete_df = pd.merge(EPL_2022_merged_df, EPL_2022_summary2_df, how="left", on=['Squad'])
EPL_2023_complete_df = pd.merge(EPL_2023_merged_df, EPL_2023_summary2_df, how="left", on=['Squad'])
EPL_2014_complete_df.head()

In [ ]:
#Get columns
EPL_2014_complete_df.columns

In [ ]:
# Select desired columns for final summary table
EPL_2013_sum_complete_df = EPL_2013_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'Attendance']]

EPL_2014_sum_complete_df = EPL_2014_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'Attendance']]

EPL_2015_sum_complete_df = EPL_2015_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'Attendance']]

EPL_2016_sum_complete_df = EPL_2016_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'Attendance']]

EPL_2017_sum_complete_df = EPL_2017_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'Attendance']]

EPL_2018_sum_complete_df = EPL_2018_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'Attendance']]

EPL_2019_sum_complete_df = EPL_2019_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'Attendance']]

EPL_2020_sum_complete_df = EPL_2020_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'Attendance']]

EPL_2021_sum_complete_df = EPL_2021_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'Attendance']]

EPL_2022_sum_complete_df = EPL_2022_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'Attendance']]

EPL_2023_sum_complete_df = EPL_2023_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages','MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 
                                                   'Pts/MP', 'Attendance']]

EPL_2023_sum_complete_df.head()

In [ ]:
# Rename columns
EPL_2013_sum_complete_df = EPL_2013_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                     '# Pl_x': '# of Players', 'MP_x': 'MP'})

EPL_2014_sum_complete_df = EPL_2014_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP'})

EPL_2015_sum_complete_df = EPL_2015_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP'})

EPL_2016_sum_complete_df = EPL_2016_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP'})

EPL_2017_sum_complete_df = EPL_2017_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP'})

EPL_2018_sum_complete_df = EPL_2018_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP'})

EPL_2019_sum_complete_df = EPL_2019_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP'})

EPL_2020_sum_complete_df = EPL_2020_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP'})

EPL_2021_sum_complete_df = EPL_2021_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP'})

EPL_2022_sum_complete_df = EPL_2022_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP'})


EPL_2023_sum_complete_df = EPL_2023_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age', 
                                                                    'Poss': 'Avg Poss', 
                                                                    '# Pl_x': '# of Players', 'MP_x': 'MP'})
EPL_2014_sum_complete_df.head()

In [ ]:
# Convert 'Annual Wages' column into single column with only dollar value
#EPL_2013_sum_complete_df[['pounds', 'dollars']] = EPL_2013_sum_complete_df['Annual Wages'].str.split('$', expand=True)
EPL_2014_sum_complete_df[['pounds', 'dollars']] = EPL_2014_sum_complete_df['Annual Wages'].str.split('$', expand=True)
EPL_2015_sum_complete_df[['pounds', 'dollars']] = EPL_2015_sum_complete_df['Annual Wages'].str.split('$', expand=True)
EPL_2016_sum_complete_df[['pounds', 'dollars']] = EPL_2016_sum_complete_df['Annual Wages'].str.split('$', expand=True)
EPL_2017_sum_complete_df[['pounds', 'dollars']] = EPL_2017_sum_complete_df['Annual Wages'].str.split('$', expand=True)
EPL_2018_sum_complete_df[['pounds', 'dollars']] = EPL_2018_sum_complete_df['Annual Wages'].str.split('$', expand=True)
EPL_2019_sum_complete_df[['pounds', 'dollars']] = EPL_2019_sum_complete_df['Annual Wages'].str.split('$', expand=True)
EPL_2020_sum_complete_df[['pounds', 'dollars']] = EPL_2020_sum_complete_df['Annual Wages'].str.split('$', expand=True)
EPL_2021_sum_complete_df[['pounds', 'dollars']] = EPL_2021_sum_complete_df['Annual Wages'].str.split('$', expand=True)
EPL_2022_sum_complete_df[['pounds', 'dollars']] = EPL_2022_sum_complete_df['Annual Wages'].str.split('$', expand=True)
EPL_2023_sum_complete_df[['pounds', 'dollars']] = EPL_2023_sum_complete_df['Annual Wages'].str.split('$', expand=True)

In [ ]:
# Convert 'Annual Wages' column into single column with only dollar value
#EPL_2013_sum_complete_df[['Annual Wages ($)', 'discard']] = EPL_2013_sum_complete_df['dollars'].str.split(')', expand=True)
EPL_2014_sum_complete_df[['Annual Wages ($)', 'discard']] = EPL_2014_sum_complete_df['dollars'].str.split(')', expand=True)
EPL_2015_sum_complete_df[['Annual Wages ($)', 'discard']] = EPL_2015_sum_complete_df['dollars'].str.split(')', expand=True)
EPL_2016_sum_complete_df[['Annual Wages ($)', 'discard']] = EPL_2016_sum_complete_df['dollars'].str.split(')', expand=True)
EPL_2017_sum_complete_df[['Annual Wages ($)', 'discard']] = EPL_2017_sum_complete_df['dollars'].str.split(')', expand=True)
EPL_2018_sum_complete_df[['Annual Wages ($)', 'discard']] = EPL_2018_sum_complete_df['dollars'].str.split(')', expand=True)
EPL_2019_sum_complete_df[['Annual Wages ($)', 'discard']] = EPL_2019_sum_complete_df['dollars'].str.split(')', expand=True)
EPL_2020_sum_complete_df[['Annual Wages ($)', 'discard']] = EPL_2020_sum_complete_df['dollars'].str.split(')', expand=True)
EPL_2021_sum_complete_df[['Annual Wages ($)', 'discard']] = EPL_2021_sum_complete_df['dollars'].str.split(')', expand=True)
EPL_2022_sum_complete_df[['Annual Wages ($)', 'discard']] = EPL_2022_sum_complete_df['dollars'].str.split(')', expand=True)
EPL_2023_sum_complete_df[['Annual Wages ($)', 'discard']] = EPL_2023_sum_complete_df['dollars'].str.split(')', expand=True)
EPL_2014_sum_complete_df.head()

In [ ]:
# Drop unwanted columns 
#EPL_2013_sum_cleaned_df = EPL_2013_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
EPL_2014_sum_cleaned_df = EPL_2014_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
EPL_2015_sum_cleaned_df = EPL_2015_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
EPL_2016_sum_cleaned_df = EPL_2016_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
EPL_2017_sum_cleaned_df = EPL_2017_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
EPL_2018_sum_cleaned_df = EPL_2018_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
EPL_2019_sum_cleaned_df = EPL_2019_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
EPL_2020_sum_cleaned_df = EPL_2020_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
EPL_2021_sum_cleaned_df = EPL_2021_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
EPL_2022_sum_cleaned_df = EPL_2022_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
EPL_2023_sum_cleaned_df = EPL_2023_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)

In [ ]:
# Sort by league position
#EPL_2013_sum_clean_sorted_df = EPL_2013_sum_cleaned_df.sort_values('Pts', ascending=False)
EPL_2014_sum_clean_sorted_df = EPL_2014_sum_cleaned_df.sort_values('Pts', ascending=False)
EPL_2015_sum_clean_sorted_df = EPL_2015_sum_cleaned_df.sort_values('Pts', ascending=False)
EPL_2016_sum_clean_sorted_df = EPL_2016_sum_cleaned_df.sort_values('Pts', ascending=False)
EPL_2017_sum_clean_sorted_df = EPL_2017_sum_cleaned_df.sort_values('Pts', ascending=False)
EPL_2018_sum_clean_sorted_df = EPL_2018_sum_cleaned_df.sort_values('Pts', ascending=False)
EPL_2019_sum_clean_sorted_df = EPL_2019_sum_cleaned_df.sort_values('Pts', ascending=False)
EPL_2020_sum_clean_sorted_df = EPL_2020_sum_cleaned_df.sort_values('Pts', ascending=False)
EPL_2021_sum_clean_sorted_df = EPL_2021_sum_cleaned_df.sort_values('Pts', ascending=False)
EPL_2022_sum_clean_sorted_df = EPL_2022_sum_cleaned_df.sort_values('Pts', ascending=False)
EPL_2023_sum_clean_sorted_df = EPL_2023_sum_cleaned_df.sort_values('Pts', ascending=False)

In [ ]:
# Create new column 'season'
#EPL_2013_sum_clean_sorted_df['Season'] = '2012-2013'
EPL_2014_sum_clean_sorted_df['Season'] = '2013-2014'
EPL_2015_sum_clean_sorted_df['Season'] = '2014-2015'
EPL_2016_sum_clean_sorted_df['Season'] = '2015-2016'
EPL_2017_sum_clean_sorted_df['Season'] = '2016-2017'
EPL_2018_sum_clean_sorted_df['Season'] = '2017-2018'
EPL_2019_sum_clean_sorted_df['Season'] = '2018-2019'
EPL_2020_sum_clean_sorted_df['Season'] = '2019-2020'
EPL_2021_sum_clean_sorted_df['Season'] = '2020-2021'
EPL_2022_sum_clean_sorted_df['Season'] = '2021-2022'
EPL_2023_sum_clean_sorted_df['Season'] = '2022-2023'
EPL_2023_sum_clean_sorted_df.head()

In [ ]:
# Concatenate all seasons into one dataframe
EPL_all_seasons_sum_df = pd.concat([EPL_2014_sum_clean_sorted_df, EPL_2015_sum_clean_sorted_df, EPL_2016_sum_clean_sorted_df, 
                                    EPL_2017_sum_clean_sorted_df, EPL_2018_sum_clean_sorted_df, 
                                    EPL_2019_sum_clean_sorted_df, EPL_2020_sum_clean_sorted_df,
                                    EPL_2021_sum_clean_sorted_df, EPL_2022_sum_clean_sorted_df, 
                                    EPL_2023_sum_clean_sorted_df], axis=0)
EPL_all_seasons_sum_df.info()

In [ ]:
# Export cleaned data to csv files
EPL_all_seasons_sum_df.to_csv('../Data/EPL_all_seasons_sum.csv', encoding= 'utf-8')

In [ ]:
EPL_all_seasons_sum_df['Annual Wages ($)'] = EPL_all_seasons_sum_df['Annual Wages ($)'].astype(str)
EPL_all_seasons_sum_df['Annual Wages ($)'] = EPL_all_seasons_sum_df['Annual Wages ($)'].map(lambda x: x.replace(',', ''))
EPL_all_seasons_sum_df['Annual Wages ($)'] = EPL_all_seasons_sum_df['Annual Wages ($)'].astype(float)
EPL_all_seasons_sum_df('Season')['Annual Wages ($)'].mean()

In [ ]:
# Get individual matches from each of the last 5 seasons
matches_18 = pd.read_html('https://fbref.com/en/comps/9/2017-2018/schedule/2017-2018-Premier-League-Scores-and-Fixtures')
EPL_2018_matches_df = pd.DataFrame(matches_18[0])

In [ ]:
# Get individual matches from each of the last 5 seasons
matches_19 = pd.read_html('https://fbref.com/en/comps/9/2018-2019/schedule/2018-2019-Premier-League-Scores-and-Fixtures')
EPL_2019_matches_df = pd.DataFrame(matches_19[0])

In [ ]:
# Get individual matches from each of the last 5 seasons
matches_20 = pd.read_html('https://fbref.com/en/comps/9/2019-2020/schedule/2019-2020-Premier-League-Scores-and-Fixtures')
EPL_2020_matches_df = pd.DataFrame(matches_20[0])

In [ ]:
# Get individual matches from each of the last 5 seasons
matches_21 = pd.read_html('https://fbref.com/en/comps/9/2020-2021/schedule/2020-2021-Premier-League-Scores-and-Fixtures')
EPL_2021_matches_df = pd.DataFrame(matches_21[0])

In [ ]:
# Get individual matches from each of the last 5 seasons
matches_22 = pd.read_html('https://fbref.com/en/comps/9/2021-2022/schedule/2021-2022-Premier-League-Scores-and-Fixtures')
EPL_2022_matches_df = pd.DataFrame(matches_22[0])
EPL_2022_matches_df.info()

In [ ]:
# Drop empty rows
# EPL_all_matches_df.dropna(how='all')
EPL_2018_matches_df = EPL_2018_matches_df.dropna(how='all')
EPL_2019_matches_df = EPL_2019_matches_df.dropna(how='all')
EPL_2020_matches_df = EPL_2020_matches_df.dropna(how='all')
EPL_2021_matches_df = EPL_2021_matches_df.dropna(how='all')
EPL_2022_matches_df = EPL_2022_matches_df.dropna(how='all')

In [ ]:
# Drop match report & notes columns
EPL_2018_matches_df = EPL_2018_matches_df.drop(['Match Report', 'Notes'], axis=1)
EPL_2019_matches_df = EPL_2019_matches_df.drop(['Match Report', 'Notes'], axis=1)
EPL_2020_matches_df = EPL_2020_matches_df.drop(['Match Report', 'Notes'], axis=1)
EPL_2021_matches_df = EPL_2021_matches_df.drop(['Match Report', 'Notes'], axis=1)
EPL_2022_matches_df = EPL_2022_matches_df.drop(['Match Report', 'Notes'], axis=1)
EPL_2022_matches_df.head()

In [ ]:
# Add seasons column
EPL_2018_matches_df['Season'] = '2017-2018'
EPL_2019_matches_df['Season'] = '2018-2019'
EPL_2020_matches_df['Season'] = '2019-2020'
EPL_2021_matches_df['Season'] = '2020-2021'
EPL_2022_matches_df['Season'] = '2021-2022'
EPL_2022_matches_df.head()

In [ ]:
# Concatenate matches into one dataframe
EPL_all_seasons_matches_df = pd.concat([EPL_2018_matches_df, EPL_2019_matches_df, EPL_2020_matches_df,
                                EPL_2021_matches_df, EPL_2022_matches_df], axis=0)
EPL_all_seasons_matches_df.info()

In [ ]:
# Split 'Score' column into 'Home Score' & 'Away Score'
EPL_all_seasons_matches_df[['Home Score','Away Score']] = EPL_all_seasons_matches_df['Score'].str.split('–', expand=True)
EPL_all_seasons_matches_df.head()

In [ ]:
# Re-organize column order
EPL_all_seasons_matches_df = EPL_all_seasons_matches_df[['Season', 'Wk', 'Date','Time', 'Home', 'Away', 'Home Score', 'Away Score', 'xG', 'xG.1',
                                       'Attendance', 'Venue', 'Referee']]

EPL_all_seasons_matches_df.head()

In [ ]:
# Create xG, actual goal differential & league ID columns
EPL_all_seasons_matches_df = EPL_all_seasons_matches_df.rename(columns={ 'xG': 'xG Home', 'xG.1': 'xG Away'}) 


EPL_all_seasons_matches_df['xG Diff'] = EPL_all_seasons_matches_df['xG Home'].astype(float) - EPL_all_seasons_matches_df['xG Away'].astype(float)
EPL_all_seasons_matches_df['Actual Diff'] = EPL_all_seasons_matches_df['Home Score'].astype(float) - EPL_all_seasons_matches_df['Away Score'].astype(float)
EPL_all_seasons_matches_df['League'] = 'EPL'
EPL_all_seasons_matches_df.head()

In [ ]:
# Re-organize column order & re-set index
EPL_all_seasons_sum_df
EPL_all_seasons_sum_df = EPL_all_seasons_sum_df[['Season', 'League Rank', 'Squad', '# of Players', 'Avg Age', 'Avg Poss', 'MP',
       'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP', 'xG', 'xGA', 'xGD',
       'xGD/90', 'Attendance', 'Annual Wages ($)']]
EPL_all_seasons_sum_df = EPL_all_seasons_sum_df.reset_index(drop=True)
EPL_all_seasons_sum_df.tail()

In [ ]:
# Remove comma from wages column to allow for conversion to float
EPL_all_seasons_sum_df['Annual Wages ($)'] = EPL_all_seasons_sum_df['Annual Wages ($)'].map(lambda x: x.replace(',', ''))
EPL_all_seasons_sum_df.head()

In [ ]:
# Create 'league' to differentiate league ID
EPL_all_seasons_sum_df['League'] = 'EPL'
EPL_all_seasons_sum_df.head()

In [ ]:
# Convert wages column to float
EPL_all_seasons_sum_df['Annual Wages ($)'] = EPL_all_seasons_sum_df['Annual Wages ($)'].astype(float)

In [ ]:
# Export cleaned data to csv files
EPL_all_seasons_sum_df.to_csv('Scapping Data/EPL_all_seasons_sum.csv', encoding= 'utf-8')
# EPL_all_seasons_matches_df.to_csv('Scrapping Data/EPL_all_seasons_matches.csv', encoding= 'utf-8')