In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import scipy.stats as stats
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
#url for Summary Stats seasons 2012_2013 to 2021_2022
url_1213_summary = "https://fbref.com/en/comps/11/2012-2013/2012-2013-Serie-A-Stats"
url_1314_summary = "https://fbref.com/en/comps/11/2013-2014/2013-2014-Serie-A-Stats"
url_1415_summary = "https://fbref.com/en/comps/11/2014-2015/2014-2015-Serie-A-Stats"
url_1516_summary = "https://fbref.com/en/comps/11/2015-2016/2015-2016-Serie-A-Stats"
url_1617_summary = "https://fbref.com/en/comps/11/2016-2017/2016-2017-Serie-A-Stats"
url_1718_summary = "https://fbref.com/en/comps/11/2017-2018/2017-2018-Serie-A-Stats"
url_1819_summary = "https://fbref.com/en/comps/11/2018-2019/2018-2019-Serie-A-Stats"
url_1920_summary = "https://fbref.com/en/comps/11/2019-2020/2019-2020-Serie-A-Stats"
url_2021_summary = "https://fbref.com/en/comps/11/2020-2021/2020-2021-Serie-A-Stats"
url_2122_summary = "https://fbref.com/en/comps/11/2021-2022/2021-2022-Serie-A-Stats"

#  Read the url
table_1213 = pd.read_html(url_1213_summary)
table_1314 = pd.read_html(url_1314_summary)
table_1415 = pd.read_html(url_1415_summary)
table_1516 = pd.read_html(url_1516_summary)
table_1617 = pd.read_html(url_1617_summary)
table_1718 = pd.read_html(url_1718_summary)
table_1819 = pd.read_html(url_1819_summary)
table_1920 = pd.read_html(url_1920_summary)
table_2021 = pd.read_html(url_2021_summary)
table_2122 = pd.read_html(url_2122_summary)


#  Create the DataFrames
serie_a_summary_1213_df = pd.DataFrame(table_1213[0])
serie_a_summary_1314_df = pd.DataFrame(table_1314[0])
serie_a_summary_1415_df = pd.DataFrame(table_1415[0])
serie_a_summary_1516_df = pd.DataFrame(table_1516[0])
serie_a_summary_1617_df = pd.DataFrame(table_1617[0])
serie_a_summary_1718_df = pd.DataFrame(table_1718[0])
serie_a_summary_1819_df = pd.DataFrame(table_1819[0])
serie_a_summary_1920_df = pd.DataFrame(table_1920[0])
serie_a_summary_2021_df = pd.DataFrame(table_2021[0])
serie_a_summary_2122_df = pd.DataFrame(table_2122[0])

In [3]:
# Get Team age (index[2])
#  Read the url
table_1213 = pd.read_html(url_1213_summary)
table_1314 = pd.read_html(url_1314_summary)
table_1415 = pd.read_html(url_1415_summary)
table_1516 = pd.read_html(url_1516_summary)
table_1617 = pd.read_html(url_1617_summary)
table_1718 = pd.read_html(url_1718_summary)
table_1819 = pd.read_html(url_1819_summary)
table_1920 = pd.read_html(url_1920_summary)
table_2021 = pd.read_html(url_2021_summary)
table_2122 = pd.read_html(url_2122_summary)


#  Create the DataFrames
serie_a_team_age_1213_df = pd.DataFrame(table_1213[2])
serie_a_team_age_1314_df = pd.DataFrame(table_1314[2])
serie_a_team_age_1415_df = pd.DataFrame(table_1415[2])
serie_a_team_age_1516_df = pd.DataFrame(table_1516[2])
serie_a_team_age_1617_df = pd.DataFrame(table_1617[2])
serie_a_team_age_1718_df = pd.DataFrame(table_1718[2])
serie_a_team_age_1819_df = pd.DataFrame(table_1819[2])
serie_a_team_age_1920_df = pd.DataFrame(table_1920[2])
serie_a_team_age_2021_df = pd.DataFrame(table_2021[2])
serie_a_team_age_2122_df = pd.DataFrame(table_2122[2])

In [4]:
# Remove upper level to allow for merging with other tables
serie_a_team_age_1213_df = serie_a_team_age_1213_df.droplevel(0, axis = 1)
serie_a_team_age_1314_df = serie_a_team_age_1314_df.droplevel(0, axis = 1)
serie_a_team_age_1415_df = serie_a_team_age_1415_df.droplevel(0, axis = 1)
serie_a_team_age_1516_df = serie_a_team_age_1516_df.droplevel(0, axis = 1)
serie_a_team_age_1617_df = serie_a_team_age_1617_df.droplevel(0, axis = 1)
serie_a_team_age_1718_df = serie_a_team_age_1718_df.droplevel(0, axis = 1)
serie_a_team_age_1819_df = serie_a_team_age_1819_df.droplevel(0, axis = 1)
serie_a_team_age_1920_df = serie_a_team_age_1920_df.droplevel(0, axis = 1)
serie_a_team_age_2021_df = serie_a_team_age_2021_df.droplevel(0, axis = 1)
serie_a_team_age_2122_df = serie_a_team_age_2122_df.droplevel(0, axis = 1)
serie_a_team_age_2122_df.head()

,Squad,# Pl,Age,Poss,MP,Starts,Min,90s,Gls,Ast,...,Gls,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG
0,Atalanta,32,27.5,55.0,38,418,3420,38.0,62,48,...,1.63,1.26,2.89,1.50,2.76,1.64,1.28,2.92,1.53,2.81
1,Bologna,36,26.6,50.6,38,418,3420,38.0,43,34,...,1.13,0.89,2.03,1.03,1.92,1.18,0.88,2.06,1.08,1.96
2,Cagliari,33,26.5,44.5,38,418,3420,38.0,34,26,...,0.89,0.68,1.58,0.82,1.50,1.03,0.78,1.81,0.96,1.74
3,Empoli,28,24.5,47.4,38,418,3420,38.0,47,27,...,1.24,0.71,1.95,1.05,1.76,1.18,0.76,1.94,1.04,1.80
4,Fiorentina,28,26.4,57.7,38,418,3420,38.0,59,33,...,1.55,0.87,2.42,1.32,2.18,1.58,1.03,2.61,1.34,2.37

In [5]:
#url for Team Wages seasons 2012_2013 to 2021_2022
url_1213_wages = "https://fbref.com/en/comps/11/2012-2013/wages/2012-2013-Serie-A-Wages"
url_1314_wages = "https://fbref.com/en/comps/11/2013-2014/wages/2013-2014-Serie-A-Wages"
url_1415_wages = "https://fbref.com/en/comps/11/2014-2015/wages/2014-2015-Serie-A-Wages"
url_1516_wages = "https://fbref.com/en/comps/11/2015-2016/wages/2015-2016-Serie-A-Wages"
url_1617_wages = "https://fbref.com/en/comps/11/2016-2017/wages/2016-2017-Serie-A-Wages"
url_1718_wages = "https://fbref.com/en/comps/11/2017-2018/wages/2017-2018-Serie-A-Wages"
url_1819_wages = "https://fbref.com/en/comps/11/2018-2019/wages/2018-2019-Serie-A-Wages"
url_1920_wages = "https://fbref.com/en/comps/11/2019-2020/wages/2019-2020-Serie-A-Wages"
url_2021_wages = "https://fbref.com/en/comps/11/2020-2021/wages/2020-2021-Serie-A-Wages"
url_2122_wages = "https://fbref.com/en/comps/11/2021-2022/wages/2021-2022-Serie-A-Wages"

#  Read the url
table_1213 = pd.read_html(url_1213_wages)
table_1314 = pd.read_html(url_1314_wages)
table_1415 = pd.read_html(url_1415_wages)
table_1516 = pd.read_html(url_1516_wages)
table_1617 = pd.read_html(url_1617_wages)
table_1718 = pd.read_html(url_1718_wages)
table_1819 = pd.read_html(url_1819_wages)
table_1920 = pd.read_html(url_1920_wages)
table_2021 = pd.read_html(url_2021_wages)
table_2122 = pd.read_html(url_2122_wages)

#  Create the DataFrames
serie_a_wages_1213_df = pd.DataFrame(table_1213[0])
serie_a_wages_1314_df = pd.DataFrame(table_1314[0])
serie_a_wages_1415_df = pd.DataFrame(table_1415[0])
serie_a_wages_1516_df = pd.DataFrame(table_1516[0])
serie_a_wages_1617_df = pd.DataFrame(table_1617[0])
serie_a_wages_1718_df = pd.DataFrame(table_1718[0])
serie_a_wages_1819_df = pd.DataFrame(table_1819[0])
serie_a_wages_1920_df = pd.DataFrame(table_1920[0])
serie_a_wages_2021_df = pd.DataFrame(table_2021[0])
serie_a_wages_2122_df = pd.DataFrame(table_2122[0])

In [6]:
# Merge wages and season summary for each season
serie_a_1213_merged_df = pd.merge(serie_a_summary_1213_df, serie_a_wages_1213_df, how="left", on=['Squad'])
serie_a_1314_merged_df = pd.merge(serie_a_summary_1314_df, serie_a_wages_1314_df, how="left", on=['Squad'])
serie_a_1415_merged_df = pd.merge(serie_a_summary_1415_df, serie_a_wages_1415_df, how="left", on=['Squad'])
serie_a_1516_merged_df = pd.merge(serie_a_summary_1516_df, serie_a_wages_1516_df, how="left", on=['Squad'])
serie_a_1617_merged_df = pd.merge(serie_a_summary_1617_df, serie_a_wages_1617_df, how="left", on=['Squad'])
serie_a_1718_merged_df = pd.merge(serie_a_summary_1718_df, serie_a_wages_1718_df, how="left", on=['Squad'])
serie_a_1819_merged_df = pd.merge(serie_a_summary_1819_df, serie_a_wages_1819_df, how="left", on=['Squad'])
serie_a_1920_merged_df = pd.merge(serie_a_summary_1920_df, serie_a_wages_1920_df, how="left", on=['Squad'])
serie_a_2021_merged_df = pd.merge(serie_a_summary_2021_df, serie_a_wages_2021_df, how="left", on=['Squad'])
serie_a_2122_merged_df = pd.merge(serie_a_summary_2122_df, serie_a_wages_2122_df, how="left", on=['Squad'])
serie_a_2122_merged_df

,Rk_x,Squad,MP,W,D,L,GF,GA,GD,Pts,...,xGD/90,Attendance,Top Team Scorer,Goalkeeper,Notes,Rk_y,# Pl,Weekly Wages,Annual Wages,% Estimated
0,1,Milan,38,26,8,4,69,31,38,86,...,0.63,44015,"Olivier Giroud, Rafael Leão - 11",Mike Maignan,→ Champions League via league finish,5,86,"€ 1,684,423 (£ 1,412,403, $1,716,615)","€ 87,590,000 (£ 73,444,949, $89,263,995)",2%
1,2,Inter,38,25,9,4,84,32,52,84,...,1.12,44473,Lautaro Martínez - 21,Samir Handanović,→ Champions League via league finish,2,81,"€ 2,950,769 (£ 2,474,245, $3,007,163)","€ 153,440,000 (£ 128,660,726, $156,372,498)",9%
2,3,Napoli,38,24,7,7,74,31,43,79,...,0.67,28119,Victor Osimhen - 14,David Ospina,→ Champions League via league finish,3,78,"€ 1,989,231 (£ 1,667,987, $2,027,248)","€ 103,440,000 (£ 86,735,304, $105,416,919)",8%
3,4,Juventus,38,20,10,8,57,37,20,70,...,0.35,22621,Paulo Dybala - 10,Wojciech Szczęsny,→ Champions League via league finish,1,76,"€ 3,479,808 (£ 2,917,848, $3,546,313)","€ 180,950,000 (£ 151,728,092, $184,408,264)",0%
4,5,Lazio,38,18,10,10,77,58,19,64,...,0.20,23263,Ciro Immobile - 27,Thomas Strakosha,→ Europa League via league finish,6,90,"€ 1,508,462 (£ 1,264,858, $1,537,291)","€ 78,440,000 (£ 65,772,599, $79,939,123)",4%
5,6,Roma,38,18,9,11,59,43,16,63,...,0.70,41929,Tammy Abraham - 17,Rui Patrício,→ Europa League via league finish,4,93,"€ 1,914,423 (£ 1,605,260, $1,951,011)","€ 99,550,000 (£ 83,473,512, $101,452,572)",11%
6,7,Fiorentina,38,19,5,14,59,51,8,62,...,0.51,21107,Dušan Vlahović - 17,Pietro Terracciano,→ Europa Conference League via league finish,7,85,"€ 1,128,846 (£ 946,547, $1,150,420)","€ 58,700,000 (£ 49,220,441, $59,821,859)",13%
7,8,Atalanta,38,16,11,11,65,48,17,59,...,0.45,10447,Mario Pašalić - 13,Juan Musso,NaN,9,76,"€ 891,346 (£ 747,401, $908,381)","€ 46,350,000 (£ 38,864,860, $47,235,829)",7%
8,9,Hellas Verona,38,14,11,13,65,59,6,53,...,0.04,13894,Giovanni Simeone - 17,Lorenzo Montipò,NaN,19,85,"€ 413,269 (£ 346,530, $421,168)","€ 21,490,000 (£ 18,019,544, $21,900,711)",22%
9,10,Torino,38,13,11,14,46,41,5,50,...,0.26,9846,Andrea Belotti - 8,Vanja Milinković-Savić,NaN,8,88,"€ 1,029,808 (£ 863,502, $1,049,489)","€ 53,550,000 (£ 44,902,122, $54,573,434)",17%
10,11,Sassuolo,38,13,11,14,64,66,-2,50,...,-0.28,8362,Gianluca Scamacca - 16,Andrea Consigli,NaN,15,86,"€ 533,846 (£ 447,634, $544,049)","€ 27,760,000 (£ 23,276,991, $28,290,540)",17%
11,12,Udinese,38,11,14,13,61,58,3,47,...,-0.03,12144,Gerard Deulofeu - 13,Marco Silvestri,NaN,18,86,"€ 430,962 (£ 361,365, $439,198)","€ 22,410,000 (£ 18,790,971, $22,838,290)",38%
12,13,Bologna,38,12,10,16,44,55,-11,46,...,-0.20,14158,Marko Arnautović - 14,Łukasz Skorupski,NaN,14,90,"€ 579,423 (£ 485,851, $590,497)","€ 30,130,000 (£ 25,264,256, $30,705,835)",30%
13,14,Empoli,38,10,11,17,50,70,-20,41,...,-0.56,6356,Andrea Pinamonti - 13,Guglielmo Vicario,NaN,12,87,"€ 710,192 (£ 595,502, $723,765)","€ 36,930,000 (£ 30,966,112, $37,635,795)",16%
14,15,Sampdoria,38,10,6,22,46,63,-17,36,...,-0.51,9417,Francesco Caputo - 11,Emil Audero,NaN,11,86,"€ 721,154 (£ 604,694, $734,936)","€ 37,500,000 (£ 31,444,064, $38,216,686)",14%
15,16,Spezia,38,10,6,22,41,71,-30,36,...,-0.64,6709,Daniele Verde - 8,Ivan Provedel,NaN,20,89,"€ 318,462 (£ 267,033, $324,548)","€ 16,560,000 (£ 13,885,700, $16,876,489)",33%
16,17,Salernitana,38,7,10,21,33,78,-45,31,...,-0.76,15073,Federico Bonazzoli - 10,Vid Belec,NaN,16,102,"€ 443,269 (£ 371,685, $451,741)","€ 23,050,000 (£ 19,327,618, $23,490,524)",48%
17,18,Cagliari,38,6,12,20,34,68,-34,30,...,-0.58,9718,João Pedro - 13,Alessio Cragno,Relegated,13,86,"€ 649,231 (£ 544,385, $661,639)","€ 33,760,000 (£ 28,308,043, $34,405,212)",33%
18,19,Genoa,38,4,16,18,27,60,-33,28,...,-0.44,12326,Mattia Destro - 9,Salvatore Sirigu,Relegated,10,106,"€ 813,462 (£ 682,094, $829,008)","€ 42,300,000 (£ 35,468,904, $43,108,428)",38%
19,20,Venezia,38,6,9,23,34,69,-35,27,...,-0.93,6648,Thomas Henry - 9,Niki Mäenpää,Relegated,17,105,"€ 440,962 (£ 369,750, $449,389)","€ 22,930,000 (£ 19,226,999, $23,368,232)",35%

In [19]:
#  Merge the Age tables for each season
serie_a_1213_complete_df = pd.merge(serie_a_1213_merged_df, serie_a_team_age_1213_df, how="left", on=["Squad"])
serie_a_1314_complete_df = pd.merge(serie_a_1314_merged_df, serie_a_team_age_1314_df, how="left", on=["Squad"])
serie_a_1415_complete_df = pd.merge(serie_a_1415_merged_df, serie_a_team_age_1415_df, how="left", on=["Squad"])
serie_a_1516_complete_df = pd.merge(serie_a_1516_merged_df, serie_a_team_age_1516_df, how="left", on=["Squad"])
serie_a_1617_complete_df = pd.merge(serie_a_1617_merged_df, serie_a_team_age_1617_df, how="left", on=["Squad"])
serie_a_1718_complete_df = pd.merge(serie_a_1718_merged_df, serie_a_team_age_1718_df, how="left", on=["Squad"])
serie_a_1819_complete_df = pd.merge(serie_a_1819_merged_df, serie_a_team_age_1819_df, how="left", on=["Squad"])
serie_a_1920_complete_df = pd.merge(serie_a_1920_merged_df, serie_a_team_age_1920_df, how="left", on=["Squad"])
serie_a_2021_complete_df = pd.merge(serie_a_2021_merged_df, serie_a_team_age_2021_df, how="left", on=["Squad"])
serie_a_2122_complete_df = pd.merge(serie_a_2122_merged_df, serie_a_team_age_2122_df, how="left", on=["Squad"])
serie_a_1213_complete_df.columns

Index(['Rk_x', 'Squad', 'MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts',
       'Pts/MP', 'xG_x', 'xGA', 'xGD', 'xGD/90', 'Attendance',
       'Top Team Scorer', 'Goalkeeper', 'Notes', 'Rk_y', '# Pl_x',
       'Weekly Wages', 'Annual Wages', '% Estimated', '# Pl_y', 'Age', 'Poss',
       'MP_y', 'Starts', 'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'CrdY', 'CrdR', 'xG_y', 'npxG', 'xAG', 'npxG+xAG', 'PrgC',
       'PrgP', 'Gls', 'Ast', 'G+A', 'G-PK', 'G+A-PK', 'xG_y', 'xAG', 'xG+xAG',
       'npxG', 'npxG+xAG'],
      dtype='object')

In [21]:
# Select desired columns for final summary table
serie_a_1213_sum_complete_df = serie_a_1213_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages',
                                                         'MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts','Pts/MP',
                                                          'Attendance']]
serie_a_1314_sum_complete_df = serie_a_1314_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages',
                                                         'MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts','Pts/MP',
                                                          'Attendance']]
serie_a_1415_sum_complete_df = serie_a_1415_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages',
                                                         'MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts','Pts/MP',
                                                          'Attendance']]
serie_a_1516_sum_complete_df = serie_a_1516_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages',
                                                         'MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts','Pts/MP',
                                                          'Attendance']]
serie_a_1617_sum_complete_df = serie_a_1617_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages',
                                                         'MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts','Pts/MP',
                                                          'Attendance']]
serie_a_1718_sum_complete_df = serie_a_1718_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages',
                                                         'MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts','Pts/MP',
                                                          'Attendance']]
serie_a_1819_sum_complete_df = serie_a_1819_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages',
                                                         'MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts','Pts/MP',
                                                          'Attendance']]
serie_a_1920_sum_complete_df = serie_a_1920_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages',
                                                         'MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts','Pts/MP',
                                                          'Attendance']]
serie_a_2021_sum_complete_df = serie_a_2021_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages',
                                                         'MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts','Pts/MP',
                                                          'Attendance']]
serie_a_2122_sum_complete_df = serie_a_2122_complete_df[['Rk_y', 'Squad','# Pl_x', 'Age', 'Poss', 'Annual Wages',
                                                         'MP_x', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts','Pts/MP',
                                                          'Attendance']]

In [22]:
# Rename columns
serie_a_1213_sum_complete_df = serie_a_1213_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age',
                                                                             'Poss': 'Avg Poss', '# Pl_x': '# of Players',
                                                                             'MP_x': 'MP',})
serie_a_1314_sum_complete_df = serie_a_1314_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age',
                                                                             'Poss': 'Avg Poss', '# Pl_x': '# of Players',
                                                                             'MP_x': 'MP',})
serie_a_1415_sum_complete_df = serie_a_1415_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age',
                                                                             'Poss': 'Avg Poss', '# Pl_x': '# of Players',
                                                                             'MP_x': 'MP',})
serie_a_1516_sum_complete_df = serie_a_1516_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age',
                                                                             'Poss': 'Avg Poss', '# Pl_x': '# of Players',
                                                                             'MP_x': 'MP',})
serie_a_1617_sum_complete_df = serie_a_1617_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age',
                                                                             'Poss': 'Avg Poss', '# Pl_x': '# of Players',
                                                                             'MP_x': 'MP',})
serie_a_1718_sum_complete_df = serie_a_1718_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age',
                                                                             'Poss': 'Avg Poss', '# Pl_x': '# of Players',
                                                                             'MP_x': 'MP',})
serie_a_1819_sum_complete_df = serie_a_1819_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age',
                                                                             'Poss': 'Avg Poss', '# Pl_x': '# of Players',
                                                                             'MP_x': 'MP',})
serie_a_1920_sum_complete_df = serie_a_1920_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age',
                                                                             'Poss': 'Avg Poss', '# Pl_x': '# of Players',
                                                                             'MP_x': 'MP', })
serie_a_2021_sum_complete_df = serie_a_2021_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age',
                                                                             'Poss': 'Avg Poss', '# Pl_x': '# of Players',
                                                                             'MP_x': 'MP', })
serie_a_2122_sum_complete_df = serie_a_2122_sum_complete_df.rename(columns={ 'Rk_y': 'League Rank', 'Age': 'Avg Age',
                                                                             'Poss': 'Avg Poss', '# Pl_x': '# of Players',
                                                                             'MP_x': 'MP',})

In [23]:
# Convert 'Annual Wages' column into single column with only dollar value
serie_a_1213_sum_complete_df[['pounds', 'dollars']] = serie_a_1213_sum_complete_df['Annual Wages'].str.split('$', expand=True)
serie_a_1314_sum_complete_df[['pounds', 'dollars']] = serie_a_1314_sum_complete_df['Annual Wages'].str.split('$', expand=True)
serie_a_1415_sum_complete_df[['pounds', 'dollars']] = serie_a_1415_sum_complete_df['Annual Wages'].str.split('$', expand=True)
serie_a_1516_sum_complete_df[['pounds', 'dollars']] = serie_a_1516_sum_complete_df['Annual Wages'].str.split('$', expand=True)
serie_a_1617_sum_complete_df[['pounds', 'dollars']] = serie_a_1617_sum_complete_df['Annual Wages'].str.split('$', expand=True)
serie_a_1718_sum_complete_df[['pounds', 'dollars']] = serie_a_1718_sum_complete_df['Annual Wages'].str.split('$', expand=True)
serie_a_1819_sum_complete_df[['pounds', 'dollars']] = serie_a_1819_sum_complete_df['Annual Wages'].str.split('$', expand=True)
serie_a_1920_sum_complete_df[['pounds', 'dollars']] = serie_a_1920_sum_complete_df['Annual Wages'].str.split('$', expand=True)
serie_a_2021_sum_complete_df[['pounds', 'dollars']] = serie_a_2021_sum_complete_df['Annual Wages'].str.split('$', expand=True)
serie_a_2122_sum_complete_df[['pounds', 'dollars']] = serie_a_2122_sum_complete_df['Annual Wages'].str.split('$', expand=True)

In [24]:
# Convert 'Annual Wages' column into single column with only dollar value

serie_a_1213_sum_complete_df[['Annual Wages ($)', 'discard']] = serie_a_1213_sum_complete_df['dollars'].str.split(')', expand=True)
serie_a_1314_sum_complete_df[['Annual Wages ($)', 'discard']] = serie_a_1314_sum_complete_df['dollars'].str.split(')', expand=True)
serie_a_1415_sum_complete_df[['Annual Wages ($)', 'discard']] = serie_a_1415_sum_complete_df['dollars'].str.split(')', expand=True)
serie_a_1516_sum_complete_df[['Annual Wages ($)', 'discard']] = serie_a_1516_sum_complete_df['dollars'].str.split(')', expand=True)
serie_a_1516_sum_complete_df[['Annual Wages ($)', 'discard']] = serie_a_1617_sum_complete_df['dollars'].str.split(')', expand=True)
serie_a_1718_sum_complete_df[['Annual Wages ($)', 'discard']] = serie_a_1718_sum_complete_df['dollars'].str.split(')', expand=True)
serie_a_1819_sum_complete_df[['Annual Wages ($)', 'discard']] = serie_a_1819_sum_complete_df['dollars'].str.split(')', expand=True)
serie_a_1920_sum_complete_df[['Annual Wages ($)', 'discard']] = serie_a_1920_sum_complete_df['dollars'].str.split(')', expand=True)
serie_a_2021_sum_complete_df[['Annual Wages ($)', 'discard']] = serie_a_2021_sum_complete_df['dollars'].str.split(')', expand=True)
serie_a_2122_sum_complete_df[['Annual Wages ($)', 'discard']] = serie_a_2122_sum_complete_df['dollars'].str.split(')', expand=True)

In [25]:
# Drop unwanted columns
serie_a_1213_sum_cleaned_df = serie_a_1213_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
serie_a_1314_sum_cleaned_df = serie_a_1314_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
serie_a_1415_sum_cleaned_df = serie_a_1415_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
serie_a_1516_sum_cleaned_df = serie_a_1516_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
serie_a_1617_sum_cleaned_df = serie_a_1718_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
serie_a_1718_sum_cleaned_df = serie_a_1718_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
serie_a_1819_sum_cleaned_df = serie_a_1819_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
serie_a_1920_sum_cleaned_df = serie_a_1920_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
serie_a_2021_sum_cleaned_df = serie_a_2021_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)
serie_a_2122_sum_cleaned_df = serie_a_2122_sum_complete_df.drop(['pounds', 'dollars', 'Annual Wages', 'discard'], axis=1)

In [26]:
# Sort by league position
serie_a_1213_sum_clean_sorted_df = serie_a_1213_sum_cleaned_df.sort_values('Pts', ascending=False)
serie_a_1314_sum_clean_sorted_df = serie_a_1314_sum_cleaned_df.sort_values('Pts', ascending=False)
serie_a_1415_sum_clean_sorted_df = serie_a_1415_sum_cleaned_df.sort_values('Pts', ascending=False)
serie_a_1516_sum_clean_sorted_df = serie_a_1516_sum_cleaned_df.sort_values('Pts', ascending=False)
serie_a_1617_sum_clean_sorted_df = serie_a_1617_sum_cleaned_df.sort_values('Pts', ascending=False)
serie_a_1718_sum_clean_sorted_df = serie_a_1718_sum_cleaned_df.sort_values('Pts', ascending=False)
serie_a_1819_sum_clean_sorted_df = serie_a_1819_sum_cleaned_df.sort_values('Pts', ascending=False)
serie_a_1920_sum_clean_sorted_df = serie_a_1920_sum_cleaned_df.sort_values('Pts', ascending=False)
serie_a_2021_sum_clean_sorted_df = serie_a_2021_sum_cleaned_df.sort_values('Pts', ascending=False)
serie_a_2122_sum_clean_sorted_df = serie_a_2122_sum_cleaned_df.sort_values('Pts', ascending=False)

In [27]:
# Add season to each DataFram
serie_a_1213_sum_clean_sorted_df['Season'] = '2012-2013'
serie_a_1314_sum_clean_sorted_df['Season'] = '2013-2014'
serie_a_1415_sum_clean_sorted_df['Season'] = '2014-2015'
serie_a_1516_sum_clean_sorted_df['Season'] = '2015-2016'
serie_a_1617_sum_clean_sorted_df['Season'] = '2016-2017'
serie_a_1718_sum_clean_sorted_df['Season'] = '2017-2018'
serie_a_1819_sum_clean_sorted_df['Season'] = '2018-2019'
serie_a_1920_sum_clean_sorted_df['Season'] = '2019-2020'
serie_a_2021_sum_clean_sorted_df['Season'] = '2020-2021'
serie_a_2122_sum_clean_sorted_df['Season'] = '2021-2022'

In [28]:
# Create a single DataFrame for Seasons Summary
serie_a_seasons_sum_df = pd.concat([serie_a_1213_sum_clean_sorted_df,serie_a_1314_sum_clean_sorted_df,serie_a_1415_sum_clean_sorted_df,
                                    serie_a_1516_sum_clean_sorted_df,serie_a_1617_sum_clean_sorted_df,serie_a_1718_sum_clean_sorted_df,
                                    serie_a_1819_sum_clean_sorted_df,serie_a_1920_sum_clean_sorted_df,serie_a_2021_sum_clean_sorted_df,
                                    serie_a_2122_sum_clean_sorted_df])

In [31]:
#  Rearrange Columns and reset index
serie_a_seasons_sum_df = serie_a_seasons_sum_df[['Season', 'League Rank', 'Squad', '# of Players', 'Avg Age',
                                                 'Avg Poss', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD', 'Pts', 'Pts/MP',
                                                 'Attendance', 'Annual Wages ($)']]

serie_a_seasons_sum_df['Annual Wages ($)'] = serie_a_seasons_sum_df['Annual Wages ($)'].map(lambda x: x.replace(',', ''))

serie_a_seasons_sum_df['Annual Wages ($)']=serie_a_seasons_sum_df['Annual Wages ($)'].astype(float)
serie_a_seasons_sum_df["League"] = "Serie A"
serie_a_seasons_sum_df = serie_a_seasons_sum_df.reset_index()
serie_a_seasons_sum_df.groupby('Season')["Annual Wages ($)"].mean()

Season
2012-2013    40306375.50
2013-2014    35451938.50
2014-2015    31577427.20
2015-2016    37881449.30
2016-2017    43633366.30
2017-2018    43633366.30
2018-2019    62537378.30
2019-2020    63229257.75
2020-2021    64384930.10
2021-2022    59966061.75
Name: Annual Wages ($), dtype: float64

In [58]:
# Export cleaned data to csv files
serie_a_seasons_sum_df.to_csv('serie_a_seasons_sum.csv', index=False)